apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnel
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name:  cloudflare-tunnel
  strategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  template:    
    metadata:
      labels:
        app.kubernetes.io/name:  cloudflare-tunnel
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ping_group_range
            value: "65532 65532"
      containers:
      - name: cloudflare-tunnel
        image: "cloudflare/cloudflared:2025.2.1"
        imagePullPolicy: IfNotPresent
        args:
        - tunnel
        - --no-autoupdate
        - --metrics
        - "0.0.0.0:9327"                
        - --protocol
        - http2
        - --retries
        - "2"
        - run
        - --token
        - $(CF_MANAGED_TUNNEL_TOKEN)
        env:
        - name: CF_MANAGED_TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-tunnel-token
              key: token
        ports:
         - name: metrics
           containerPort: 9327
        resources:
          requests:
            cpu: 250m       
            memory: 128Mi    
          limits:
            cpu: 375m       
            memory: 192Mi
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /ready
            port: 9327
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      priorityClassName: system-cluster-critical
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name:  cloudflare-tunnel
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name:  cloudflare-tunnel
              topologyKey: kubernetes.io/hostname
            weight: 100