---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app.kubernetes.io/name:  cloudflare-tunnel
  creationTimestamp: null
  name: cloudflare-tunnel-token
  namespace: kube-system
spec:
  encryptedData:
    token: AQBF7/ljdYg+KHcPZmGFEKl3MHVOvVMyzOhtwHDpFVNWRdxhefyk/EbTnZAqtO9hGFim/kXfPJK+4khWo2WMOKRIevD1N+ezFocESUCnbxL5jPX5j+EE6NE7/LERDqWily3Yls3xLbl8NUWh1UaBu61UgC8MdaRWpJtH6SDkDFrGHjPQJiiwWq/MKzhuJ2vVA0yoN9LjKoTGnpwy3YQcr+S3KXG0H2rT0repHc9Cg2uv00VXIDQSczbrLTEw3W8OCroeBXX8BfYNbp8SckKr32MCYCbpT5WuyCz8ltvOkII9CFvykYXn4L4Z6DBI+Iu0Qgocvl8+UZgzM3CCE71jDRPHtywwYJLUsr4kcLULM9s8qUetRDqeyqBKGJj0Jx9vs2d5QN70tua7K9lsaV78RsJDknPDbFytxxE1uG6vLdFxeoejzFpGv+yk7Oqd9Qg2yENmU+aIpI1YWBAcWU/yKkBcOV0HBJjVzrEkvLNa884P7sQ5oV6lbBCQMU5cD2wyZ7+J62m8KdIh265RPoSyFEIIUdg5fOqhc4KgB3d0tqAJcWNCid/fwj6GtQ0uc8iq5ooEU7TwXY4oRIAwEqjTfzN0ypKbsQG2Ac0=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-token
      namespace: kube-system
