apiVersion: v1
kind: Service
metadata:
  name: "cloudflare-tunnel-metrics"
  namespace: kube-system
  labels:
    app.kubernetes.io/name:  cloudflare-tunnel
spec:
  selector:
    app.kubernetes.io/name:  cloudflare-tunnel
  ports:
    - protocol: TCP
      port: 9327
      targetPort: 9327
      name: metrics