---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: newrelic-license-secret
  namespace: monitoring
spec:
  encryptedData:
    license: AQB8ufObNMhLfES13dIpw7iPYxxFk8BHUu/toRD/EB+/Mj5yOb8mA8/CC4rl9h/xD5icFD0J/g1Bea83av4R5UzpEEZtYqd1VwHbbazZRKTJvOf954rFRGcVVe4sIjQKsbVIYsdn1KtXrdqt0OQxf9sXB+hDyqJIOpQI9JfpbahgEz2daum22RV9yBnxgF5DhOnoog/3mX9sRpYBYAkdnJx7EfiQoxAB14aM+sjEqnLbx7Lbt8PaJ8x58s9gYEXMaeH8PpA3b9dOX21jcKCXotTweESqLLUXnY26kBC8Bcy3ZKpo0cMgTCUC+doiVIxiFmJfrIZn1ZsXj19ZmI3tS6WnQe6sywQw9XIvOU6Dm/hK9q8Pp3h3muvUVfmDJjBFwbqAHBbxdnu+dyxnjr4Prwg6DSLGioQFdM8=
  template:
    metadata:
      creationTimestamp: null
      name: newrelic-license-secret
      namespace: monitoring
