mariadb:
  architecture: standalone
  auth:
    database: gpmlogin
    username: admin
    existingSecret: mariadb-secret
  primary:
    priorityClassName: gpmlogin-server-critical  
    persistence:
      size: 1Gi
      storageClass: local-path
    nodeSelector: 
      kubernetes.io/hostname: node1
    resources:
      requests:
        cpu: 500
        memory: 512Mi
      limits:
        cpu: 750
        memory: 768Mi

    configuration: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      datadir=/bitnami/mariadb/data
      plugin_dir=/opt/bitnami/mariadb/plugin
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=*
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      slow_query_log=0
      long_query_time=10.0
      binlog_expire_logs_seconds=2592000

      # Optimize RAM (~450MB , maximize 768MB)
      innodb_buffer_pool_size=350M  # Main Cache
      innodb_log_buffer_size=6M     # Log buffer
      # Optimize CPU & I/O
      innodb_thread_concurrency=3
      thread_cache_size=4  
      max_connections=30 

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mariadb/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
