apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: headlamp
    repo: https://headlamp-k8s.github.io/headlamp
    version: 0.28.1
    namespace: system-tools
    releaseName: headlamp
    additionalValuesFiles:  
      - values.yaml
