k8s-monitoring:
  cluster:
    name: default
  destinations:
    - name: grafana-cloud-metrics
      type: prometheus
      url: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push
      auth:
        type: basic      
        usernameKey: prom-username
        passwordKey: access-token
      secret:
        create: false
        name: grafana-cloud-credentials
        namespace: monitoring
    - name: grafana-cloud-logs
      type: loki
      url: https://logs-prod-020.grafana.net/loki/api/v1/push
      auth:
        type: basic              
        usernameKey: loki-username
        passwordKey: access-token
      secret:
        create: false
        name: grafana-cloud-credentials
        namespace: monitoring
  clusterMetrics:
    enabled: true
    opencost:
      enabled: false
  annotationAutodiscovery:
    enabled: true
  prometheusOperatorObjects:
    enabled: true
  clusterEvents:
    enabled: true
  nodeLogs:
    enabled: true
  podLogs:
    enabled: true
  integrations:
    alloy:
      instances:
        - name: alloy
          labelSelectors:
            app.kubernetes.io/name:
              - alloy-metrics
              - alloy-singleton
              - alloy-logs
  alloy-metrics:
    enabled: true
  alloy-singleton:
    enabled: true
  alloy-logs:
    enabled: true
