metrics-server:
  apiService:
    create: true   
  extraArgs:
    - --kubelet-insecure-tls=true
    - --kubelet-preferred-address-types=InternalIP
    - --metric-resolution=30s  
  pdb:
    create: true
    minAvailable: 1
  updateStrategy:
    rollingUpdate:
      maxSurge: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 150m
      memory: 192Mi
