---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AQAef1fOez1nHpZ0zBxBjVmsXhOrVxgmV05uQ87uX3UGB/qnECQ+12FBZq3fhBuA7yENArEV6N+DxgVFvH/Q6o3XSm0209DZqESVJ1rJTXPzhrdoETax+pBmiAck1ax9a2N9y+o4qbWNwMDSEUh+gw5J6sPJPZBp8KLOVsyX21lX76WQcawlw8goPMub/Uq3If/JsVRZ2k6SabhzmtGcvK2vKYjXT49+Qqeinvis668g1m9swmMSMELWp578HTCjZ3hHKjXjqwzLFn4OMDKAxmiKZABwFPdRNd1enySFtaVYKaExsJLjRLp/4rWkfWAqVDIP7L+8Z8762qODo1ffttkQYWiG7E4l4DoEb3rhsFkuhlndiqFnolnzSb8aRmPMtyH6hzxnAdWKdxCoN0Z5VN7a
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: keycloak
