---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AQBf3vc9TY5r9p/d1Qm+O0OB+KV+YaoaMKbgiGZfgBW/jP8/JKz7CJx2OG9KvhBBbnllWDWYbf5BTHj++HNUeTB4q582SMXfjlReuLNTlSC2R3H3j+7SNAaabKyaUirSJLbxd0vGKfOL1xymgdi7gLhgxG9DgA8KuHKhta1gzEtNz9g0zz0chaFUZ2zXWL0FsfxPyXow+rhHYVGUEmd3u/+YrT4kBHh87OQeFm/WQ2ZM5WULvTKeWufFJPDC9QFRtLxUTMGyXsPdrl/1opSdhYdju9B484H/Oa2lz+iEkSldxQ5RsEUq+7axYeLSkCpXTM8l8VG5elsrKfvcn2+BoBwU5OYA/wPF+hGv10sA5OFpww1T3YWUkIJgaC3Q88DVcBk=
    postgres-password: AQCLzQPvDOsOoWJ8/Ic3uFe5KnLnX/wGucfhOLud1mLQJzTH4z/ZzdXcpsf0Rzi3ytsUYzvAWuJ1HePQZMfSZqI7RGsnMZlrcsHwE+XGWrKj/TF4aB41Z9Loz0JkcG3DU+MvifpQpEXWZn2sR+grr+MPUm+bdl+JXbqiqwagPHOgSdJxm253UrJgiUyWsSfhF4nIhCSBFAB8GJteQOWmFS/Av5fLH/khTKgZpznW5shT2R7ZuUkuTMUV/s+jbGAdk6n1XDCPKuyKPqC8d1eX5pv5fiiQItapvSgo9bpLNRGlwD1Bm+6zBiQ6cEi9xaWdC0WKY2/VAOAyhAJ5ytXNI6IB943jeGvYZX4YWWd6FgKy3/6/bo5RRgShQLNwj5j/nHVYTFJmTsfTVKSaUfKxnA==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: keycloak
