apiVersion: v2
name: kube-state-metrics
version: 1.0.0
dependencies:
- name: kube-state-metrics  
  version: 5.30.1
  repository: https://prometheus-community.github.io/helm-charts
  alias: kms