provisioner:
  fullnameOverride: local-path-provisioner
  priorityClassName: system-node-critical
  resources:
    requests:
      cpu: 50m
      memory: 48Mi
    limits:
      cpu: 75m
      memory: 72Mi
  classes:
    - name: local-storage
      hostDir: /data/local-path-provisioner
      volumeMode: Filesystem
      fsType: ext4
      namePattern: "*"
      allowedTopologies:
      blockCleanerCommand:
        - "/scripts/shred.sh"
        - "2"      
      storageClass:
        reclaimPolicy: Delete
