apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: dev-cluster
servers: 1 
agents: 2
options:
  k3d:
    wait: true    
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=servicelb
        nodeFilters:
          - server:*    
      - arg: --disable=traefik
        nodeFilters:
          - server:*            
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*    