apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: descheduler
    repo: https://kubernetes-sigs.github.io/descheduler
    version: 0.32.2
    releaseName: descheduler    
    namespace: kube-system
